"""Contract tests for the replay routes (CLAUDE.md 12; task P2.7).

The bundles here are folders with a manifest and empty members: ``GET /v1/replay/bundles``
reports which members are *present*, and ``varuna bundle validate`` is what reads them. That
split is deliberate, so the replay page can say "Generated by make bundle" about a folder that
does not exist yet without loading a Zarr store to find out.
"""

from __future__ import annotations

import json
import time
from collections.abc import Iterator
from datetime import datetime, timedelta
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from varuna_api.state import AppState
from varuna_cycle.bus import Bus
from varuna_schemas.constants import IST
from varuna_schemas.models.bundle import BundleManifest, BundleSource
from varuna_schemas.models.city import RadarDomain
from varuna_schemas.models.common import BBox

BUNDLE_ID = "MUM-2019-07-02"
DESIGN_ID = "MUM-IDF-25yr"
T0 = datetime(2019, 7, 2, 5, 40, tzinfo=IST)
T1 = datetime(2019, 7, 2, 9, 40, tzinfo=IST)
AOI = BBox(min_lon=72.815, min_lat=18.995, max_lon=72.905, max_lat=19.135)
RADAR = RadarDomain(center_lon=72.86, center_lat=19.065, size_km=60.0, res_m=500.0)
CADENCES = {
    "radar": 10,
    "truth": 5,
    "gauges": 15,
    "tide": 15,
    "traffic": 5,
    "reports": 5,
    "cycle": 5,
}

MEMBERS = (
    "radar/frames.zarr",
    "truth/rain.zarr",
    "gauges.csv",
    "tide.csv",
    "traffic/speeds.parquet",
    "reports.jsonl",
    "ground_truth.geojson",
)


def _manifest(bundle_id: str, label: str) -> BundleManifest:
    sources = (
        [
            BundleSource(
                name="IMD Santacruz 24-hour total, 2 July 2019",
                url="https://mausam.imd.gov.in/mumbai/mcdata/Highest_Scz_July.gif",
                note="375.2 mm for the 24 hours ending 08:30 IST",
                used_for="Window accumulation target",
            )
        ]
        if label == "Reconstructed replay"
        else []
    )
    return BundleManifest(
        id=bundle_id,
        city="mumbai",
        label=label,  # type: ignore[arg-type]
        t0=T0,
        t1=T1,
        cadences=CADENCES,
        radar_domain=RADAR,
        aoi=AOI,
        sources=sources,
        seed=2019,
        synthetic_notes=["Radar frames: storm-designer reconstruction."],
        ground_truth_n=29,
        description="Reconstructed replay of the 2 July 2019 morning.",
    )


def _write_bundle(root: Path, bundle_id: str, label: str, *, complete: bool) -> Path:
    folder = root / bundle_id
    folder.mkdir(parents=True, exist_ok=True)
    manifest = _manifest(bundle_id, label)
    (folder / "manifest.json").write_text(
        manifest.model_dump_json(indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    if complete:
        for member in MEMBERS:
            path = folder / member
            path.parent.mkdir(parents=True, exist_ok=True)
            if member.endswith(".zarr"):
                path.mkdir(exist_ok=True)
            else:
                path.write_text("", encoding="utf-8", newline="\n")
    return folder


@pytest.fixture
def bundles(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A bundles folder holding one complete-looking bundle and one that is only a manifest."""
    root = tmp_path / "bundles"
    monkeypatch.setenv("VARUNA_BUNDLES_DIR", str(root))
    _write_bundle(root, BUNDLE_ID, "Reconstructed replay", complete=True)
    _write_bundle(root, DESIGN_ID, "Design storm", complete=False)
    return root


@pytest.fixture
def client(app: FastAPI, bundles: Path) -> Iterator[TestClient]:
    """The API with the temporary bundles folder in place before the app starts."""
    with TestClient(app) as test_client:
        yield test_client


def test_bundles_lists_what_is_on_disk_with_build_and_bake_status(client: TestClient) -> None:
    rows = client.get("/v1/replay/bundles").json()
    assert [row["id"] for row in rows] == [BUNDLE_ID, DESIGN_ID]  # sorted by id

    demo = next(row for row in rows if row["id"] == BUNDLE_ID)
    assert demo["label"] == "Reconstructed replay"
    assert demo["city"] == "mumbai"
    assert demo["t0"] == T0.isoformat()
    assert demo["t1"] == T1.isoformat()
    assert demo["built"] is True
    assert demo["missing_members"] == []
    assert demo["total_cycles"] == 49  # 4 hours of 5-minute cycles, inclusive
    assert demo["baked"] is False
    assert demo["baked_cycles"] == 0
    assert demo["ground_truth_n"] == 29
    assert demo["sources_n"] == 1

    design = next(row for row in rows if row["id"] == DESIGN_ID)
    assert design["built"] is False
    assert design["missing_members"] == ["radar/frames.zarr", "truth/rain.zarr"]


def test_bundles_is_empty_when_none_is_generated(
    app: FastAPI, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("VARUNA_BUNDLES_DIR", str(tmp_path / "nothing-here"))
    with TestClient(app) as client:
        assert client.get("/v1/replay/bundles").json() == []


def test_a_baked_cycle_counts_towards_the_bake_status(
    client: TestClient, baked_run: object, state: AppState
) -> None:
    """``baked_run`` writes one run.json; the bundle it names is the demo bundle."""
    row = next(r for r in client.get("/v1/replay/bundles").json() if r["id"] == BUNDLE_ID)
    assert row["baked_cycles"] == 1
    assert row["baked"] is False


def test_clock_opens_the_configured_bundle_paused_at_t0(client: TestClient) -> None:
    clock = client.get("/v1/replay/clock").json()
    assert clock["bundle_id"] == BUNDLE_ID
    assert clock["sim_time"] == T0.isoformat()
    assert clock["playing"] is False
    assert clock["speed"] == 30
    assert clock["mode"] == "baked"
    assert clock["cycle_index"] == 0
    assert clock["n_cycles"] == 49
    assert clock["progress"] == 0.0


def test_play_and_pause_move_the_shared_clock(client: TestClient) -> None:
    played = client.post("/v1/replay/play").json()
    assert played["playing"] is True

    paused = client.post("/v1/replay/pause").json()
    assert paused["playing"] is False
    assert paused["sim_time"] >= T0.isoformat()
    assert client.get("/v1/replay/clock").json()["sim_time"] == paused["sim_time"]


def test_seek_clamps_to_the_window_instead_of_refusing(client: TestClient) -> None:
    inside = (T0 + timedelta(minutes=60)).isoformat()
    assert client.post("/v1/replay/seek", json={"sim_time": inside}).json()["sim_time"] == inside

    late = client.post("/v1/replay/seek", json={"sim_time": "2019-07-02T23:00:00+05:30"}).json()
    assert late["sim_time"] == T1.isoformat()

    early = client.post("/v1/replay/seek", json={"sim_time": "2019-07-01T00:00:00+05:30"}).json()
    assert early["sim_time"] == T0.isoformat()


def test_speed_accepts_what_the_time_bar_offers_and_explains_what_it_does_not(
    client: TestClient,
) -> None:
    assert client.post("/v1/replay/speed", json={"speed": 60}).json()["speed"] == 60

    res = client.post("/v1/replay/speed", json={"speed": 7})
    assert res.status_code == 422
    error = res.json()["error"]
    assert error["code"] == "invalid_speed"
    assert "1, 10, 30, 60" in error["message"]
    assert client.get("/v1/replay/clock").json()["speed"] == 60


def test_selecting_another_bundle_moves_the_clock_to_its_window(client: TestClient) -> None:
    clock = client.post("/v1/replay/bundle", json={"bundle_id": DESIGN_ID}).json()
    assert clock["bundle_id"] == DESIGN_ID
    assert clock["playing"] is False
    assert client.get("/v1/replay/clock").json()["bundle_id"] == DESIGN_ID


def test_an_unknown_bundle_says_which_make_target_generates_it(client: TestClient) -> None:
    res = client.post("/v1/replay/bundle", json={"bundle_id": "MUM-2020-08-05"})
    assert res.status_code == 404
    error = res.json()["error"]
    assert error["code"] == "bundle_not_found"
    assert "make bundle BUNDLE=MUM-2020-08-05" in error["message"]
    assert BUNDLE_ID in error["message"]  # what is on disk instead

    assert client.get("/v1/replay/clock", params={"bundle": "MUM-2020-08-05"}).status_code == 404


def test_health_reports_the_clock_once_it_is_open(client: TestClient) -> None:
    assert client.get("/healthz").json()["replay"] is None
    client.get("/v1/replay/clock")
    replay = client.get("/healthz").json()["replay"]
    assert replay["bundle_id"] == BUNDLE_ID
    assert replay["t0"] == T0.isoformat()


def test_the_clock_state_reaches_the_console_over_the_websocket(
    client: TestClient, bus: Bus
) -> None:
    with client.websocket_connect("/v1/live") as ws:
        assert ws.receive_json()["topic"] == "hello"
        # The relay task subscribes after the handshake; publishing before it does would be a
        # race the console never runs into (it subscribes once and stays).
        deadline = time.monotonic() + 2
        while bus.subscriber_count == 0 and time.monotonic() < deadline:
            time.sleep(0.01)

        target = (T0 + timedelta(minutes=45)).isoformat()
        client.post("/v1/replay/seek", json={"sim_time": target})

        # The socket also carries heartbeats (every 0.2 s in tests); skip them.
        for _ in range(10):
            event = ws.receive_json()
            if event["topic"] == "replay.clock":
                break
        assert event["topic"] == "replay.clock"
        assert event["payload"]["sim_time"] == target
        assert event["payload"]["bundle_id"] == BUNDLE_ID


def test_openapi_documents_the_replay_routes(client: TestClient) -> None:
    paths = client.get("/openapi.json").json()["paths"]
    for path in (
        "/v1/replay/bundles",
        "/v1/replay/clock",
        "/v1/replay/play",
        "/v1/replay/pause",
        "/v1/replay/seek",
        "/v1/replay/speed",
        "/v1/replay/bundle",
    ):
        assert path in paths, path
    assert "501" not in paths["/v1/replay/clock"]["get"]["responses"]
    assert "404" in paths["/v1/replay/clock"]["get"]["responses"]


def test_the_manifest_on_disk_is_the_one_the_api_reports(client: TestClient, bundles: Path) -> None:
    on_disk = json.loads((bundles / BUNDLE_ID / "manifest.json").read_text(encoding="utf-8"))
    row = next(r for r in client.get("/v1/replay/bundles").json() if r["id"] == BUNDLE_ID)
    assert row["seed"] == on_disk["seed"]
    assert row["synthetic_notes"] == on_disk["synthetic_notes"]
    assert row["description"] == on_disk["description"]
