import { fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ReplayScreen } from "@/app/replay/replay-screen";
import { useReplayStore } from "@/lib/stores/replay";

vi.mock("next/navigation", () => ({
  usePathname: () => "/replay",
  useRouter: () => ({ push: vi.fn(), replace: vi.fn(), prefetch: vi.fn() }),
}));

function renderScreen() {
  return render(
    <TooltipProvider>
      <ReplayScreen />
    </TooltipProvider>,
  );
}

describe("ReplayScreen", () => {
  afterEach(() => {
    useReplayStore.getState().reset();
  });

  it("offers the three bundles and selects one into the replay store", () => {
    renderScreen();
    expect(screen.getByRole("heading", { level: 1, name: "Replay" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /MUM-2019-07-02/ })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /MUM-IDF-25yr/ })).toBeInTheDocument();

    const chennai = screen.getByRole("button", { name: /CHN-IDF-25yr/ });
    fireEvent.click(chennai);

    const state = useReplayStore.getState();
    expect(state.bundleId).toBe("CHN-IDF-25yr");
    expect(state.simTime).toBe("2026-11-05T05:40:00+05:30");
    expect(chennai).toHaveAttribute("aria-pressed", "true");
  });

  it("says a bundle is not on disk yet rather than pretending it is", () => {
    renderScreen();
    expect(screen.getAllByText("Generated by make bundle").length).toBe(3);
  });

  it("holds the cycle log and the storm designer in their empty states", () => {
    renderScreen();
    expect(screen.getByText("No cycle yet")).toBeInTheDocument();
    expect(screen.getAllByText("No cycles yet").length).toBeGreaterThan(0);
    expect(
      screen.getByText("Editing the storm is coming in pilot; the demo storm is read-only"),
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Generate bundle" })).toBeDisabled();
  });
});
